#!/usr/bin/env python3
"""Publiceer gecontroleerde TR-koppelingen voor Johannes 6 in versbatches."""

from __future__ import annotations
import argparse, json
from pathlib import Path
from rebuild_nt_tr_strongs import load_tr_chapter
from rebuild_johannes2_tr_strongs import mapping, r

ROOT = Path(__file__).resolve().parents[1]
SPECS = {
    1: [("Na deze", r(0, 1)), ("vertrok Jezus", r(2, 4)),
        ("over de zee van Galilea", r(5, 9)), ("die is de zee van Tiberias", r(10, 11))],
    2: [("En Hem volgde een grote menigte", r(0, 4)), ("omdat zij Zijn tekenen zagen", r(5, 9)),
        ("die Hij deed aan de zieken", r(10, 14))],
    3: [("En Jezus ging op de berg", r(0, 6)), ("en zat daar neer", r(7, 9)),
        ("met Zijn discipelen", r(10, 13))],
    4: [("En het pascha", [0, 1, 3, 4]), ("het feest van de Joden", r(5, 8)),
        ("was nabij", r(2))],
    5: [("Jezus dan, de ogen opheffende", r(0, 5)), ("en ziende", r(6, 7)),
        ("dat een grote menigte tot Hem kwam", r(8, 13)), ("zei tot Filippus", r(14, 17)),
        ("Vanwaar zullen wij broden kopen", r(18, 20)), ("opdat deze eten mogen", r(21, 23))],
    6: [("Maar dit zei Hij", r(0, 2)), ("hem beproevende", r(3, 4)),
        ("want Hij wist Zelf", r(5, 7)), ("wat Hij doen zou", r(8, 10))],
    7: [("Filippus antwoordde Hem", r(0, 2)), ("Voor tweehonderd penningen brood", r(3, 5)),
        ("is voor deze niet genoeg", r(6, 8)), ("opdat ieder van hen", r(9, 11)),
        ("een weinig neme", r(12, 14))],
    8: [("zei tot Hem", r(0, 1)), ("Één van Zijn discipelen", r(2, 6)),
        ("namelijk Andreas", r(7)), ("de broer van Simon Petrus", r(8, 11))],
    9: [("Hier is een jongen", r(0, 3)), ("dat vijf gerstebroden heeft", r(4, 8)),
        ("en twee visjes", r(9, 11)), ("maar wat zijn deze onder zo velen", r(12, 17))],
    10: [("En Jezus zei", r(0, 3)), ("Doe de mensen nederzitten", r(4, 7)),
         ("En er was veel gras", r(8, 11)), ("in die plaats", r(12, 14)),
         ("Zo zaten dan de mannen neer", r(15, 18)),
         ("ongeveer vijf duizend in getal", r(19, 22))],
    11: [("En Jezus nam de broden", r(0, 5)), ("en gedankt hebbende", r(6, 7)),
         ("deelde Hij ze de discipelen", r(8, 10)),
         ("en de discipelen degenen, die nedergezeten waren", r(11, 15)),
         ("evenzo ook van de visjes", r(16, 20)), ("zoveel zij wilden", r(21, 22))],
    12: [("En als zij verzadigd waren", r(0, 2)), ("zei Hij tot Zijn discipelen", r(3, 6)),
         ("Verzamelt de overgeschoten stukken brood", r(7, 10)),
         ("opdat er niets verloren ga", r(11, 14))],
    13: [("Zij verzamelden ze dan", r(0, 2)), ("en vulden twaalf manden", r(3, 5)),
         ("met stukken brood van de vijf gerstebroden", r(6, 12)),
         ("die overgeschoten waren", r(13, 14)), ("degenen, die gegeten hadden", r(15, 16))],
    14: [("De mensen dan", r(0, 2)), ("gezien hebbende het teken", [3, 6]),
         ("dat Jezus gedaan had", [4, 5, 7, 8]), ("zeiden", r(9, 10)),
         ("Deze is werkelijk de Profeet", r(11, 15)),
         ("Die in de wereld komen zou", r(16, 20))],
    15: [("Jezus dan, wetende", r(0, 2)), ("dat zij zouden komen", r(3, 5)),
         ("en Hem met geweld nemen", r(6, 8)), ("opdat zij Hem Koning maakten", r(9, 12)),
         ("ontweek opnieuw op de berg", r(13, 17)), ("Hij Zelf alleen", r(18, 19))],
    16: [("En als het avond geworden was", r(0, 3)), ("gingen Zijn discipelen af", r(4, 7)),
         ("naar de zee", r(8, 10))],
    17: [("En in het schip gegaan zijnde", r(0, 4)),
         ("kwamen zij over de zee naar Kapernaüm", r(5, 10)),
         ("En het was al duister geworden", r(11, 14)),
         ("en Jezus was tot hen niet gekomen", r(15, 21))],
    18: [("En de zee", r(0, 2)), ("verhief zich", r(6)),
         ("omdat er een grote wind waaide", r(3, 5))],
    19: [("En als zij ongeveer vijf en twintig of dertig stadiën gevaren waren", r(0, 6)),
         ("zagen zij Jezus", r(7, 9)), ("wandelende op de zee", r(10, 13)),
         ("en komende bij het schip", r(14, 18)), ("en zij werden bevreesd", r(19, 20))],
    20: [("Maar Hij zei tot hen", r(0, 3)), ("Ik ben het", r(4, 5)),
         ("wees niet bevreesd", r(6, 7))],
    21: [("Zij hebben dan Hem gewillig", r(0, 3)), ("in het schip genomen", r(4, 6)),
         ("en meteen kwam het schip", r(7, 11)), ("aan het land", r(12, 14)),
         ("daar zij naar toe voeren", r(15, 17))],
    22: [("Op de andere dag de menigte", r(0, 3)),
         ("die aan de andere zijde van de zee stond", r(4, 9)),
         ("ziende, dat daar geen ander scheepje was", r(10, 15)),
         ("dan dat ene", r(16, 19)), ("daar Zijn discipelen ingegaan waren", r(20, 25)),
         ("en dat Jezus met Zijn discipelen in dat scheepje niet was gegaan", r(26, 37)),
         ("maar dat Zijn discipelen alleen weggevaren waren", r(38, 43))],
    23: [("Maar er kwamen andere scheepjes van Tiberias", r(0, 5)),
         ("nabij de plaats", r(6, 8)), ("waar zij het brood gegeten hadden", r(9, 12)),
         ("als de Heere gedankt had", r(13, 15))],
    24: [("Toen dan de menigte zag", r(0, 4)), ("dat Jezus daar niet was", r(5, 9)),
         ("noch Zijn discipelen", r(10, 13)), ("zo gingen zij ook in de schepen", r(14, 19)),
         ("en kwamen te Kapernaüm", r(20, 23)), ("zoekende Jezus", r(24, 26))],
    25: [("En als zij Hem gevonden hadden", r(0, 2)), ("over de zee", r(3, 5)),
         ("zeiden zij tot Hem", r(6, 7)), ("Rabbi", r(8)),
         ("wanneer bent U hier gekomen", r(9, 11))],
    26: [("Jezus antwoordde hun en zei", r(0, 5)),
         ("Voorwaar, voorwaar zeg Ik u", r(6, 9)), ("u zoekt Mij", r(10, 11)),
         ("niet omdat u tekenen gezien hebt", r(12, 15)),
         ("maar omdat u van de broden gegeten hebt", r(16, 21)),
         ("en verzadigd bent", r(22, 23))],
    27: [("Werk niet om het voedsel, die vergaat", r(0, 5)),
         ("maar om het voedsel, die blijft", r(6, 10)), ("tot in het eeuwige leven", r(11, 13)),
         ("dat de Zoon des mensen u geven zal", r(14, 20)),
         ("want Deze heeft God de Vader verzegeld", r(21, 27))],
    28: [("Zij zeiden dan tot Hem", r(0, 3)), ("Wat zullen wij doen", r(4, 5)),
         ("opdat wij de werken van God mogen werken", r(6, 11))],
    29: [("Jezus antwoordde en zei tot hen", r(0, 5)),
         ("Dit is het werk van God", r(6, 11)), ("dat u gelooft in Hem", r(12, 15)),
         ("Die Hij gezonden heeft", r(16, 17))],
    30: [("Zij zeiden dan tot Hem", r(0, 2)), ("Wat teken doet U dan", r(3, 7)),
         ("opdat wij het mogen zien", r(8, 9)), ("en U geloven", r(10, 12)),
         ("Wat werkt U", r(13, 14))],
    31: [("Onze vaders", r(0, 2)), ("hebben het Manna gegeten", r(3, 5)),
         ("in de woestijn", r(6, 8)), ("zoals geschreven is", r(9, 11)),
         ("Hij gaf hun", r(16, 17)), ("het brood uit de hemel", r(12, 15)),
         ("te eten", r(18))],
    32: [("Jezus dan zei tot hen", r(0, 4)), ("Voorwaar, voorwaar zeg Ik u", r(5, 8)),
         ("Mozes heeft u niet gegeven", r(9, 12)), ("het brood uit de hemel", r(13, 17)),
         ("maar Mijn Vader geeft u", r(18, 23)),
         ("dat ware Brood uit de hemel", r(24, 30))],
    33: [("Want het Brood Gods is Hij", r(0, 6)), ("Die uit de hemel neerdaalt", r(7, 10)),
         ("en Die van de wereld het leven geeft", r(11, 15))],
    34: [("Zij zeiden dan tot Hem", r(0, 3)), ("Heere", r(4)),
         ("geef ons altijd dit Brood", r(5, 10))],
    35: [("En Jezus zei tot hen", r(0, 4)), ("Ik ben het Brood van het leven", r(5, 10)),
         ("die tot Mij komt", r(11, 14)), ("zal in geen geval hongeren", r(15, 17)),
         ("en die in Mij gelooft", r(18, 22)), ("zal nimmermeer dorsten", r(23, 26))],
    36: [("Maar Ik heb u gezegd", r(0, 2)), ("dat u Mij ook gezien hebt", r(3, 6)),
         ("en u gelooft niet", r(7, 9))],
    37: [("Al wat Mij de Vader geeft", r(0, 5)), ("zal tot Mij komen", r(6, 8)),
         ("en die tot Mij komt", r(9, 13)), ("zal Ik in geen geval uitwerpen", r(14, 17))],
    38: [("Want Ik ben uit de hemel nedergedaald", r(0, 4)),
         ("niet opdat Ik Mijn wil zou doen", r(5, 11)),
         ("maar de wil Van Degene, Die Mij gezonden heeft", r(12, 17))],
    39: [("En dit is de wil van de Vader, Die Mij gezonden heeft", r(0, 8)),
         ("dat al wat Hij Mij gegeven heeft", r(9, 13)), ("Ik daaruit niet verlieze", r(14, 17)),
         ("maar het opwekke", r(18, 20)), ("ten uitersten dage", r(21, 24))],
    40: [("En dit is de wil Van Degene, Die Mij gezonden heeft", r(0, 8)),
         ("dat ieder, die de Zoon aanschouwt", r(9, 13)), ("en in Hem gelooft", r(14, 17)),
         ("het eeuwige leven heeft", r(18, 20)), ("en Ik zal hem opwekken", r(21, 24)),
         ("ten uitersten dage", r(25, 27))],
    41: [("De Joden dan morden over Hem", r(0, 5)), ("omdat Hij gezegd had", r(6, 7)),
         ("Ik ben het Brood", r(8, 11)), ("Dat uit de hemel nedergedaald is", r(12, 16))],
    42: [("En zij zeiden", r(0, 1)), ("Is deze niet Jezus", r(2, 5)),
         ("de Zoon van Jozef", r(6, 8)), ("Wiens vader en moeder wij kennen", r(9, 16)),
         ("Hoe zegt Deze dan", r(17, 20)), ("Ik ben uit de hemel nedergedaald", r(21, 25))],
    43: [("Jezus antwoordde dan, en zei tot hen", r(0, 6)),
         ("Mort niet onder elkaar", r(7, 10))],
    44: [("Niemand kan tot Mij komen", r(0, 4)), ("tenzij dat de Vader", r(5, 8)),
         ("Die Mij gezonden heeft", r(9, 11)), ("hem trekke", r(12, 13)),
         ("en Ik zal hem opwekken", r(14, 17)), ("ten uitersten dage", r(18, 20))],
    45: [("Er is geschreven in de profeten", r(0, 4)),
         ("En zij zullen allen van God geleerd zijn", r(5, 10)),
         ("Ieder dan", r(11, 13)), ("die het van de Vader gehoord", r(14, 17)),
         ("en geleerd heeft", r(18, 19)), ("die komt tot Mij", r(20, 22))],
    46: [("Niet dat iemand de Vader gezien heeft", r(0, 5)),
         ("dan Die van God is", r(6, 12)), ("Deze heeft de Vader gezien", r(13, 16))],
    47: [("Voorwaar, voorwaar zeg Ik u", r(0, 3)), ("Die in Mij gelooft", r(4, 7)),
         ("heeft het eeuwige leven", r(8, 10))],
    48: [("Ik ben het Brood van het leven", r(0, 5))],
    49: [("Uw vaders hebben het Manna gegeten", r(0, 5)), ("in de woestijn", r(6, 8)),
         ("en zij zijn gestorven", r(9, 10))],
    50: [("Dit is het Brood", r(0, 3)), ("dat uit de hemel neerdaalt", r(4, 8)),
         ("opdat de mens daarvan eet", r(9, 13)), ("en niet sterft", r(14, 16))],
    51: [("Ik ben dat levende Brood", r(0, 5)), ("dat uit de hemel nedergedaald is", r(6, 10)),
         ("zo iemand van dit Brood eet", r(11, 17)), ("die zal in de eeuwigheid leven", r(18, 21)),
         ("En het Brood, dat Ik geven zal", r(22, 28)),
         ("is Mijn vlees, dat Ik geven zal", r(29, 35)),
         ("voor het leven van de wereld", r(36, 40))],
    52: [("De Joden dan streden onder elkaar", r(0, 5)), ("zeggende", r(6)),
         ("Hoe kan ons deze", r(7, 10)), ("Zijn vlees te eten geven", r(11, 14))],
    53: [("Jezus dan zei tot hen", r(0, 4)), ("Voorwaar, voorwaar zeg Ik u", r(5, 8)),
         ("Tenzij dat u", r(9, 10)), ("het vlees van de Zoon des mensen eet", r(11, 17)),
         ("en Zijn bloed drinkt", r(18, 22)), ("zo hebt u geen leven in uzelf", r(23, 27))],
    54: [("Die Mijn vlees eet", r(0, 4)), ("en Mijn bloed drinkt", r(5, 9)),
         ("die heeft het eeuwige leven", r(10, 12)), ("en Ik zal hem opwekken", r(13, 16)),
         ("ten uitersten dage", r(17, 19))],
    55: [("Want Mijn vlees is werkelijk Voedsel", r(0, 6)),
         ("en Mijn bloed is werkelijk Drank", r(7, 13))],
    56: [("Die Mijn vlees eet", r(0, 4)), ("en Mijn bloed drinkt", r(5, 9)),
         ("die blijft in Mij", r(10, 12)), ("en Ik in hem", r(13, 15))],
    57: [("Zoals Mij de levende Vader gezonden heeft", r(0, 5)),
         ("en Ik leeft door de Vader", r(6, 10)), ("zo die Mij eet", r(11, 14)),
         ("deze zal leven door Mij", r(15, 18))],
    58: [("Dit is het Brood", r(0, 3)), ("dat uit de hemel nedergedaald is", r(4, 8)),
         ("niet zoals uw vaders het Manna gegeten hebben", r(9, 16)),
         ("en zijn gestorven", r(17, 18)), ("Die dit Brood eet", r(19, 23)),
         ("zal in de eeuwigheid leven", r(24, 27))],
    59: [("Deze dingen zei Hij", r(0, 1)), ("in de synagoge", r(2, 3)),
         ("lerende te Kapernaüm", r(4, 6))],
    60: [("Velen dan van Zijn discipelen", [0, 1, 3, 4, 5, 6]), ("dit horende", r(2)),
         ("zeiden", r(7)), ("Deze rede is hard", r(8, 12)),
         ("wie kan deze horen", r(13, 16))],
    61: [("Jezus nu, wetende bij Zichzelf", r(0, 5)),
         ("dat Zijn discipelen daarover morden", r(6, 12)), ("zei tot hen", r(13, 14)),
         ("Doet dit u struikelen", r(15, 17))],
    62: [("Wat zou het dan zijn, zo u", r(0, 2)), ("de Zoon des mensen", r(3, 6)),
         ("zag opvaren", r(7)), ("daar Hij te voren was", r(8, 11))],
    63: [("De Geest is het, Die levend maakt", r(0, 4)),
         ("het vlees is niet nut", r(5, 9)), ("De woorden", r(10, 11)),
         ("die Ik tot u spreek", r(12, 15)), ("zijn geest", r(16, 17)),
         ("en zijn leven", r(18, 20))],
    64: [("Maar er zijn sommigen van u", r(0, 4)), ("die niet geloven", r(5, 7)),
         ("Want Jezus wist van het begin", r(8, 13)), ("wie zij waren", r(14, 16)),
         ("die niet geloofden", r(17, 18)), ("en wie hij was", r(19, 22)),
         ("die Hem verraden zou", r(23, 24))],
    65: [("En Hij zei", r(0, 1)), ("Daarom heb Ik u gezegd", r(2, 5)),
         ("dat niemand tot Mij komen kan", r(6, 11)),
         ("tenzij dat het hem gegeven zij", r(12, 16)), ("van Mijn Vader", r(17, 20))],
    66: [("Van toen af", r(0, 1)), ("gingen velen van Zijn discipelen terug", r(2, 9)),
         ("en wandelden niet meer met Hem", r(10, 14))],
    67: [("Jezus dan zei tot de twaalven", r(0, 5)),
         ("Wilt u ook niet weggaan", r(6, 10))],
    68: [("Simon Petrus dan antwoordde Hem", r(0, 4)), ("Heere", r(5)),
         ("tot Wie zullen wij heengaan", r(6, 8)),
         ("U hebt de woorden van het eeuwige leven", r(9, 12))],
    69: [("En wij hebben geloofd", r(0, 2)), ("en bekend", r(3, 4)),
         ("dat U bent de Christus", r(5, 9)), ("de Zoon van de levende God", r(10, 15))],
    70: [("Jezus antwoordde hun", r(0, 3)), ("Heb Ik niet u twaalf uitverkoren", r(4, 9)),
         ("En één uit u is een duivel", r(10, 15))],
    71: [("En Hij zei dit van Judas", r(0, 3)), ("Simons zoon, Iskariot", r(4, 5)),
         ("want deze zou Hem verraden", r(6, 10)),
         ("zijnde één van de twaalven", r(11, 15))],
}

def build(utr_path: Path, osis_path: Path, write=False):
    source = load_tr_chapter(utr_path, osis_path, chapter=6, osis_book="John")
    chapter_path = ROOT / "data" / "johannes" / "6.json"
    chapter = json.loads(chapter_path.read_text(encoding="utf-8"))
    review = {"book": "johannes", "chapter": 6, "reviewed_through": 71, "verses": {}}
    for verse in chapter["verses"][:71]:
        number = int(verse["number"]); tokens = source[number]; groups = SPECS[number]
        covered = [index for _, ids in groups for index in ids]
        if sorted(covered) != list(range(len(tokens))) or len(set(covered)) != len(tokens):
            raise ValueError(f"Johannes 6:{number}: onvolledige of dubbele handmatige review")
        verse["grondtekst"] = [{"woord": t["woord"], "strongs": t["display_strong"],
            "lemma_strongs": t["lemma_strong"], "morfologie": t["morphology"],
            **({"tvm": t["tvm"]} if t.get("tvm") else {})} for t in tokens]
        verse["woordnummers"] = [mapping(anchor, ids, tokens, number) for anchor, ids in groups]
        for item in verse["woordnummers"]: item["herkomst"]["referentie"] = f"JHN 6:{number}"
        review["verses"][str(number)] = [{"tekst": a, "bronindices": ids,
            "reviewstatus": "handmatig_gecontroleerd"} for a, ids in groups]
    if write:
        chapter_path.write_text(json.dumps(chapter, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        review_dir = ROOT / "data" / "woordnummers-review"; review_dir.mkdir(exist_ok=True)
        (review_dir / "johannes-6.json").write_text(json.dumps(review, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        inline_path = ROOT / "data" / "woordnummers-inline" / "johannes.json"
        inline = json.loads(inline_path.read_text(encoding="utf-8")); inline["chapters"]["6"] = {
            str(v["number"]): v["woordnummers"] for v in chapter["verses"][:71]}
        inline_path.write_text(json.dumps(inline, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {"verses": 71, "tokens": sum(len(source[n]) for n in range(1, 72))}

def main():
    p=argparse.ArgumentParser(); p.add_argument("--utr",type=Path,required=True); p.add_argument("--osis",type=Path,required=True); p.add_argument("--write",action="store_true")
    a=p.parse_args(); print(json.dumps(build(a.utr,a.osis,a.write),indent=2))
if __name__ == "__main__": main()
