/* De inhoud van het evangelisatietraktaat: een regel per passage.
 * Volgorde in deze lijst is de volgorde in het boekje.
 * Velden: boek (id uit data/books.json), hoofdstuk, verzen (optioneel,
 * inclusief begin en eind), titel (optioneel, overschrijft de kop).
 * Let op: de lijst zelf moet geldige JSON blijven (dubbele
 * aanhalingstekens, geen commentaar binnen de haken), omdat
 * scripts/controleer_selectie.py hem uitleest.
 */
window.TRAKTAAT_SELECTIE = [
  {"boek": "genesis", "hoofdstuk": 1},
  {"boek": "genesis", "hoofdstuk": 2},
  {"boek": "genesis", "hoofdstuk": 3},
  {"boek": "genesis", "hoofdstuk": 4},
  {"boek": "genesis", "hoofdstuk": 5},
  {"boek": "genesis", "hoofdstuk": 6},
  {"boek": "genesis", "hoofdstuk": 7},
  {"boek": "genesis", "hoofdstuk": 8},
  {"boek": "genesis", "hoofdstuk": 9},
  {"boek": "genesis", "hoofdstuk": 10},
  {"boek": "genesis", "hoofdstuk": 11},
  {"boek": "genesis", "hoofdstuk": 12},
  {"boek": "genesis", "hoofdstuk": 13},
  {"boek": "genesis", "hoofdstuk": 14},
  {"boek": "genesis", "hoofdstuk": 15},
  {"boek": "genesis", "hoofdstuk": 16},
  {"boek": "genesis", "hoofdstuk": 17},
  {"boek": "genesis", "hoofdstuk": 18},
  {"boek": "genesis", "hoofdstuk": 19},
  {"boek": "genesis", "hoofdstuk": 20},
  {"boek": "genesis", "hoofdstuk": 21},
  {"boek": "genesis", "hoofdstuk": 22},
  {"boek": "genesis", "hoofdstuk": 23},
  {"boek": "genesis", "hoofdstuk": 24},
  {"boek": "genesis", "hoofdstuk": 25},
  {"boek": "exodus", "hoofdstuk": 19},
  {"boek": "exodus", "hoofdstuk": 20},
  {"boek": "deuteronomium", "hoofdstuk": 28},
  {"boek": "richteren", "hoofdstuk": 13},
  {"boek": "richteren", "hoofdstuk": 14},
  {"boek": "richteren", "hoofdstuk": 15},
  {"boek": "richteren", "hoofdstuk": 16},
  {"boek": "1samuel", "hoofdstuk": 16},
  {"boek": "1samuel", "hoofdstuk": 17},
  {"boek": "1koningen", "hoofdstuk": 8, "verzen": [12, 66]},
  {"boek": "1koningen", "hoofdstuk": 9, "verzen": [1, 12]},
  {"boek": "job", "hoofdstuk": 1},
  {"boek": "job", "hoofdstuk": 2},
  {"boek": "job", "hoofdstuk": 3},
  {"boek": "job", "hoofdstuk": 38},
  {"boek": "job", "hoofdstuk": 39},
  {"boek": "job", "hoofdstuk": 40},
  {"boek": "job", "hoofdstuk": 41},
  {"boek": "job", "hoofdstuk": 42},
  {"boek": "psalmen", "hoofdstuk": 1},
  {"boek": "psalmen", "hoofdstuk": 2},
  {"boek": "psalmen", "hoofdstuk": 3},
  {"boek": "psalmen", "hoofdstuk": 4},
  {"boek": "psalmen", "hoofdstuk": 5},
  {"boek": "psalmen", "hoofdstuk": 6},
  {"boek": "psalmen", "hoofdstuk": 7},
  {"boek": "psalmen", "hoofdstuk": 8},
  {"boek": "psalmen", "hoofdstuk": 9},
  {"boek": "psalmen", "hoofdstuk": 10},
  {"boek": "psalmen", "hoofdstuk": 11},
  {"boek": "psalmen", "hoofdstuk": 12},
  {"boek": "psalmen", "hoofdstuk": 13},
  {"boek": "psalmen", "hoofdstuk": 14},
  {"boek": "psalmen", "hoofdstuk": 15},
  {"boek": "psalmen", "hoofdstuk": 16},
  {"boek": "psalmen", "hoofdstuk": 17},
  {"boek": "psalmen", "hoofdstuk": 18},
  {"boek": "psalmen", "hoofdstuk": 19},
  {"boek": "psalmen", "hoofdstuk": 20},
  {"boek": "psalmen", "hoofdstuk": 21},
  {"boek": "psalmen", "hoofdstuk": 22},
  {"boek": "psalmen", "hoofdstuk": 23},
  {"boek": "psalmen", "hoofdstuk": 24},
  {"boek": "psalmen", "hoofdstuk": 25},
  {"boek": "psalmen", "hoofdstuk": 119, "verzen": [1, 40]},
  {"boek": "psalmen", "hoofdstuk": 122},
  {"boek": "spreuken", "hoofdstuk": 1},
  {"boek": "spreuken", "hoofdstuk": 2},
  {"boek": "spreuken", "hoofdstuk": 3},
  {"boek": "spreuken", "hoofdstuk": 4},
  {"boek": "spreuken", "hoofdstuk": 5},
  {"boek": "spreuken", "hoofdstuk": 6},
  {"boek": "spreuken", "hoofdstuk": 7},
  {"boek": "spreuken", "hoofdstuk": 8},
  {"boek": "spreuken", "hoofdstuk": 9},
  {"boek": "spreuken", "hoofdstuk": 30},
  {"boek": "prediker", "hoofdstuk": 1},
  {"boek": "prediker", "hoofdstuk": 2},
  {"boek": "prediker", "hoofdstuk": 3},
  {"boek": "jesaja", "hoofdstuk": 1},
  {"boek": "jesaja", "hoofdstuk": 2},
  {"boek": "jesaja", "hoofdstuk": 3},
  {"boek": "jesaja", "hoofdstuk": 4},
  {"boek": "jesaja", "hoofdstuk": 5, "verzen": [1, 24]},
  {"boek": "jesaja", "hoofdstuk": 44, "verzen": [1, 8]},
  {"boek": "jesaja", "hoofdstuk": 52, "verzen": [13, 15]},
  {"boek": "jesaja", "hoofdstuk": 53},
  {"boek": "jesaja", "hoofdstuk": 55},
  {"boek": "jesaja", "hoofdstuk": 64},
  {"boek": "jesaja", "hoofdstuk": 65, "verzen": [1, 5]},
  {"boek": "jeremia", "hoofdstuk": 1, "verzen": [1, 10]},
  {"boek": "klaagliederen", "hoofdstuk": 3},
  {"boek": "ezechiel", "hoofdstuk": 28},
  {"boek": "ezechiel", "hoofdstuk": 36, "verzen": [16, 33]},
  {"boek": "daniel", "hoofdstuk": 1},
  {"boek": "daniel", "hoofdstuk": 6},
  {"boek": "daniel", "hoofdstuk": 7},
  {"boek": "daniel", "hoofdstuk": 9},
  {"boek": "daniel", "hoofdstuk": 10},
  {"boek": "hosea", "hoofdstuk": 14, "verzen": [2, 3]},
  {"boek": "jona", "hoofdstuk": 1},
  {"boek": "jona", "hoofdstuk": 2},
  {"boek": "jona", "hoofdstuk": 3},
  {"boek": "jona", "hoofdstuk": 4},
  {"boek": "gebedvanmanasse", "hoofdstuk": 1, "titel": "Gebed van Manasse"},
  {"boek": "habakuk", "hoofdstuk": 1},
  {"boek": "habakuk", "hoofdstuk": 2},
  {"boek": "zacharia", "hoofdstuk": 10},
  {"boek": "zacharia", "hoofdstuk": 14},
  {"boek": "maleachi", "hoofdstuk": 3},
  {"boek": "markus", "hoofdstuk": 1},
  {"boek": "markus", "hoofdstuk": 2},
  {"boek": "markus", "hoofdstuk": 3},
  {"boek": "markus", "hoofdstuk": 4},
  {"boek": "markus", "hoofdstuk": 5},
  {"boek": "markus", "hoofdstuk": 6},
  {"boek": "markus", "hoofdstuk": 7},
  {"boek": "markus", "hoofdstuk": 8},
  {"boek": "markus", "hoofdstuk": 9},
  {"boek": "markus", "hoofdstuk": 10},
  {"boek": "markus", "hoofdstuk": 11},
  {"boek": "markus", "hoofdstuk": 12},
  {"boek": "markus", "hoofdstuk": 13},
  {"boek": "markus", "hoofdstuk": 14},
  {"boek": "markus", "hoofdstuk": 15},
  {"boek": "markus", "hoofdstuk": 16},
  {"boek": "johannes", "hoofdstuk": 1},
  {"boek": "johannes", "hoofdstuk": 2},
  {"boek": "johannes", "hoofdstuk": 3},
  {"boek": "johannes", "hoofdstuk": 4},
  {"boek": "johannes", "hoofdstuk": 5},
  {"boek": "johannes", "hoofdstuk": 6},
  {"boek": "johannes", "hoofdstuk": 7},
  {"boek": "johannes", "hoofdstuk": 8},
  {"boek": "johannes", "hoofdstuk": 9},
  {"boek": "johannes", "hoofdstuk": 10},
  {"boek": "johannes", "hoofdstuk": 11},
  {"boek": "johannes", "hoofdstuk": 12},
  {"boek": "johannes", "hoofdstuk": 13},
  {"boek": "johannes", "hoofdstuk": 14},
  {"boek": "johannes", "hoofdstuk": 15},
  {"boek": "johannes", "hoofdstuk": 16},
  {"boek": "johannes", "hoofdstuk": 17},
  {"boek": "johannes", "hoofdstuk": 18},
  {"boek": "johannes", "hoofdstuk": 19},
  {"boek": "johannes", "hoofdstuk": 20},
  {"boek": "johannes", "hoofdstuk": 21},
  {"boek": "handelingen", "hoofdstuk": 1},
  {"boek": "handelingen", "hoofdstuk": 2},
  {"boek": "handelingen", "hoofdstuk": 3},
  {"boek": "handelingen", "hoofdstuk": 4},
  {"boek": "handelingen", "hoofdstuk": 5},
  {"boek": "handelingen", "hoofdstuk": 8},
  {"boek": "handelingen", "hoofdstuk": 9},
  {"boek": "handelingen", "hoofdstuk": 10},
  {"boek": "romeinen", "hoofdstuk": 1},
  {"boek": "romeinen", "hoofdstuk": 2},
  {"boek": "romeinen", "hoofdstuk": 3},
  {"boek": "romeinen", "hoofdstuk": 4},
  {"boek": "romeinen", "hoofdstuk": 5},
  {"boek": "romeinen", "hoofdstuk": 6},
  {"boek": "romeinen", "hoofdstuk": 7},
  {"boek": "romeinen", "hoofdstuk": 8},
  {"boek": "romeinen", "hoofdstuk": 9},
  {"boek": "romeinen", "hoofdstuk": 10},
  {"boek": "romeinen", "hoofdstuk": 11},
  {"boek": "romeinen", "hoofdstuk": 12},
  {"boek": "romeinen", "hoofdstuk": 13},
  {"boek": "romeinen", "hoofdstuk": 14},
  {"boek": "romeinen", "hoofdstuk": 15},
  {"boek": "romeinen", "hoofdstuk": 16},
  {"boek": "1korinthiers", "hoofdstuk": 12},
  {"boek": "galaten", "hoofdstuk": 5},
  {"boek": "efeziers", "hoofdstuk": 6},
  {"boek": "filippenzen", "hoofdstuk": 3},
  {"boek": "kolossenzen", "hoofdstuk": 1},
  {"boek": "kolossenzen", "hoofdstuk": 2},
  {"boek": "kolossenzen", "hoofdstuk": 3},
  {"boek": "kolossenzen", "hoofdstuk": 4},
  {"boek": "jakobus", "hoofdstuk": 1},
  {"boek": "jakobus", "hoofdstuk": 4},
  {"boek": "1johannes", "hoofdstuk": 1},
  {"boek": "1johannes", "hoofdstuk": 2},
  {"boek": "1johannes", "hoofdstuk": 3},
  {"boek": "openbaring", "hoofdstuk": 1},
  {"boek": "openbaring", "hoofdstuk": 2},
  {"boek": "openbaring", "hoofdstuk": 3},
  {"boek": "openbaring", "hoofdstuk": 4},
  {"boek": "openbaring", "hoofdstuk": 22}
];
